/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:bodyhp[MAX_PLAYERS];
new PlayerText:layarhp[MAX_PLAYERS];
new PlayerText:tombolhp[MAX_PLAYERS];
new PlayerText:merekhp[MAX_PLAYERS];
new PlayerText:tulisanmemanggil[MAX_PLAYERS];
new PlayerText:nomoryangdituju[MAX_PLAYERS];
new PlayerText:WallpaperHP[MAX_PLAYERS];
new PlayerText:tombolpanggilanhp[MAX_PLAYERS];
new PlayerText:tomboltutup[MAX_PLAYERS];

//Textdraws

//Player Textdraws
bodyhp[playerid] = CreatePlayerTextDraw(playerid, 631.000000, 101.000000, " -");
PlayerTextDrawFont(playerid, bodyhp[playerid], 0);
PlayerTextDrawLetterSize(playerid, bodyhp[playerid], 1.320837, 13.900032);
PlayerTextDrawTextSize(playerid, bodyhp[playerid], 460.000000, -25.500000);
PlayerTextDrawSetOutline(playerid, bodyhp[playerid], 0);
PlayerTextDrawSetShadow(playerid, bodyhp[playerid], 0);
PlayerTextDrawAlignment(playerid, bodyhp[playerid], 1);
PlayerTextDrawColor(playerid, bodyhp[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, bodyhp[playerid], 1296911871);
PlayerTextDrawBoxColor(playerid, bodyhp[playerid], 1296911666);
PlayerTextDrawUseBox(playerid, bodyhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, bodyhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bodyhp[playerid], 0);

layarhp[playerid] = CreatePlayerTextDraw(playerid, 615.000000, 107.000000, " -");
PlayerTextDrawFont(playerid, layarhp[playerid], 1);
PlayerTextDrawLetterSize(playerid, layarhp[playerid], 1.258334, 11.500023);
PlayerTextDrawTextSize(playerid, layarhp[playerid], 477.500000, -25.500000);
PlayerTextDrawSetOutline(playerid, layarhp[playerid], 0);
PlayerTextDrawSetShadow(playerid, layarhp[playerid], 0);
PlayerTextDrawAlignment(playerid, layarhp[playerid], 1);
PlayerTextDrawColor(playerid, layarhp[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, layarhp[playerid], 1296911871);
PlayerTextDrawBoxColor(playerid, layarhp[playerid], -206);
PlayerTextDrawUseBox(playerid, layarhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, layarhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, layarhp[playerid], 0);

tombolhp[playerid] = CreatePlayerTextDraw(playerid, 563.000000, 341.000000, " -");
PlayerTextDrawFont(playerid, tombolhp[playerid], 1);
PlayerTextDrawLetterSize(playerid, tombolhp[playerid], 1.075000, -1.199972);
PlayerTextDrawTextSize(playerid, tombolhp[playerid], 528.000000, -25.500000);
PlayerTextDrawSetOutline(playerid, tombolhp[playerid], 0);
PlayerTextDrawSetShadow(playerid, tombolhp[playerid], 0);
PlayerTextDrawAlignment(playerid, tombolhp[playerid], 1);
PlayerTextDrawColor(playerid, tombolhp[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, tombolhp[playerid], 1296911871);
PlayerTextDrawBoxColor(playerid, tombolhp[playerid], -206);
PlayerTextDrawUseBox(playerid, tombolhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, tombolhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tombolhp[playerid], 1);

merekhp[playerid] = CreatePlayerTextDraw(playerid, 546.000000, 106.000000, " Handphone");
PlayerTextDrawFont(playerid, merekhp[playerid], 3);
PlayerTextDrawLetterSize(playerid, merekhp[playerid], 0.233333, 1.450000);
PlayerTextDrawTextSize(playerid, merekhp[playerid], 400.000000, 129.000000);
PlayerTextDrawSetOutline(playerid, merekhp[playerid], 1);
PlayerTextDrawSetShadow(playerid, merekhp[playerid], 0);
PlayerTextDrawAlignment(playerid, merekhp[playerid], 2);
PlayerTextDrawColor(playerid, merekhp[playerid], -293409025);
PlayerTextDrawBackgroundColor(playerid, merekhp[playerid], 255);
PlayerTextDrawBoxColor(playerid, merekhp[playerid], 30);
PlayerTextDrawUseBox(playerid, merekhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, merekhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, merekhp[playerid], 0);

tulisanmemanggil[playerid] = CreatePlayerTextDraw(playerid, 547.000000, 143.000000, "Calling ...... ");
PlayerTextDrawFont(playerid, tulisanmemanggil[playerid], 1);
PlayerTextDrawLetterSize(playerid, tulisanmemanggil[playerid], 0.862500, 4.000000);
PlayerTextDrawTextSize(playerid, tulisanmemanggil[playerid], 416.000000, 98.000000);
PlayerTextDrawSetOutline(playerid, tulisanmemanggil[playerid], 1);
PlayerTextDrawSetShadow(playerid, tulisanmemanggil[playerid], 0);
PlayerTextDrawAlignment(playerid, tulisanmemanggil[playerid], 2);
PlayerTextDrawColor(playerid, tulisanmemanggil[playerid], 16711935);
PlayerTextDrawBackgroundColor(playerid, tulisanmemanggil[playerid], 255);
PlayerTextDrawBoxColor(playerid, tulisanmemanggil[playerid], 50);
PlayerTextDrawUseBox(playerid, tulisanmemanggil[playerid], 1);
PlayerTextDrawSetProportional(playerid, tulisanmemanggil[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tulisanmemanggil[playerid], 0);

nomoryangdituju[playerid] = CreatePlayerTextDraw(playerid, 546.000000, 189.000000, "Putu 407500");
PlayerTextDrawFont(playerid, nomoryangdituju[playerid], 3);
PlayerTextDrawLetterSize(playerid, nomoryangdituju[playerid], 0.862500, 4.000000);
PlayerTextDrawTextSize(playerid, nomoryangdituju[playerid], 416.000000, 98.000000);
PlayerTextDrawSetOutline(playerid, nomoryangdituju[playerid], 1);
PlayerTextDrawSetShadow(playerid, nomoryangdituju[playerid], 0);
PlayerTextDrawAlignment(playerid, nomoryangdituju[playerid], 2);
PlayerTextDrawColor(playerid, nomoryangdituju[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, nomoryangdituju[playerid], 255);
PlayerTextDrawBoxColor(playerid, nomoryangdituju[playerid], 50);
PlayerTextDrawUseBox(playerid, nomoryangdituju[playerid], 0);
PlayerTextDrawSetProportional(playerid, nomoryangdituju[playerid], 1);
PlayerTextDrawSetSelectable(playerid, nomoryangdituju[playerid], 0);

WallpaperHP[playerid] = CreatePlayerTextDraw(playerid, 525.000000, 246.000000, "ld_rce4:race18");
PlayerTextDrawFont(playerid, WallpaperHP[playerid], 4);
PlayerTextDrawLetterSize(playerid, WallpaperHP[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, WallpaperHP[playerid], 46.500000, 46.500000);
PlayerTextDrawSetOutline(playerid, WallpaperHP[playerid], 1);
PlayerTextDrawSetShadow(playerid, WallpaperHP[playerid], 0);
PlayerTextDrawAlignment(playerid, WallpaperHP[playerid], 1);
PlayerTextDrawColor(playerid, WallpaperHP[playerid], 16711935);
PlayerTextDrawBackgroundColor(playerid, WallpaperHP[playerid], 255);
PlayerTextDrawBoxColor(playerid, WallpaperHP[playerid], 50);
PlayerTextDrawUseBox(playerid, WallpaperHP[playerid], 1);
PlayerTextDrawSetProportional(playerid, WallpaperHP[playerid], 1);
PlayerTextDrawSetSelectable(playerid, WallpaperHP[playerid], 0);

tombolpanggilanhp[playerid] = CreatePlayerTextDraw(playerid, 481.000000, 325.000000, "HUD:radar_crash1");
PlayerTextDrawFont(playerid, tombolpanggilanhp[playerid], 4);
PlayerTextDrawLetterSize(playerid, tombolpanggilanhp[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, tombolpanggilanhp[playerid], 31.000000, 14.500000);
PlayerTextDrawSetOutline(playerid, tombolpanggilanhp[playerid], 1);
PlayerTextDrawSetShadow(playerid, tombolpanggilanhp[playerid], 0);
PlayerTextDrawAlignment(playerid, tombolpanggilanhp[playerid], 1);
PlayerTextDrawColor(playerid, tombolpanggilanhp[playerid], 16711935);
PlayerTextDrawBackgroundColor(playerid, tombolpanggilanhp[playerid], 255);
PlayerTextDrawBoxColor(playerid, tombolpanggilanhp[playerid], 50);
PlayerTextDrawUseBox(playerid, tombolpanggilanhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, tombolpanggilanhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tombolpanggilanhp[playerid], 1);

tomboltutup[playerid] = CreatePlayerTextDraw(playerid, 581.000000, 325.000000, "HUD:radar_crash1");
PlayerTextDrawFont(playerid, tomboltutup[playerid], 4);
PlayerTextDrawLetterSize(playerid, tomboltutup[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, tomboltutup[playerid], 31.000000, 14.500000);
PlayerTextDrawSetOutline(playerid, tomboltutup[playerid], 1);
PlayerTextDrawSetShadow(playerid, tomboltutup[playerid], 0);
PlayerTextDrawAlignment(playerid, tomboltutup[playerid], 1);
PlayerTextDrawColor(playerid, tomboltutup[playerid], -16776961);
PlayerTextDrawBackgroundColor(playerid, tomboltutup[playerid], 255);
PlayerTextDrawBoxColor(playerid, tomboltutup[playerid], 50);
PlayerTextDrawUseBox(playerid, tomboltutup[playerid], 1);
PlayerTextDrawSetProportional(playerid, tomboltutup[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tomboltutup[playerid], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
